#!/bin/bash
#
#  sallmond The sallmon core server.
#
#
# chkconfig: 345 80 20
# description: sallmond
# processname: sallmond
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/sallmond, see below
if [ -f /etc/sysconfig/sallmond ]; then
        . /etc/sysconfig/sallmond
fi

RETVAL=0

prog=sallmond
# you can override the lockfile via SALLMOND_LOCKFILE in /etc/sysconfig/sallmond
lockfile=${SALLMOND_LOCKFILE-/var/lock/subsys/sallmond}

# sallmond defaults to /usr/bin/sallmond, override with SALLMOND_BIN
sallmond=${SALLMOND_BIN-/usr/bin/sallmond}

# sallmond opts default to -disablewallet, override with SALLMOND_OPTS
sallmond_opts=${SALLMOND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $sallmond $sallmond_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
